name: AnarchadiaEntityLimiter
version: '${project.version}'
main: org.anarchadia.entitylimiter.Loader
api-version: '1.20'

commands:
  entitylimiter:
    description: Main command for AnarchadiaEntityLimiter
    usage: /entitylimiter reload
    aliases: [el]